// Package swagger ...
/*
 * Share my Cart
 *
 * Stay home. Stay safe. I'll bring your groceries along as I get mine.
 *
 * API version: 0.1.0
 * Contact: sharemycart@beimir.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Registration holds the Username, Email, and Password of the user
type Registration struct {
	Username string `json:"username"`

	Email string `json:"email"`

	Password string `json:"password"`
}
